name: Run Python Tests 

on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ]

jobs: 
  build-and-test:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4 # Krok 1: Pobranie kodu z Twojego repozytorium

    - name: Set up Python 3.11 # Krok 2: Konfiguracja środowiska Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install dependencies # Krok 3: Instalacja zależności
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest # Krok 4: Uruchomienie testów
      run: |
        pytest -v tests/
